apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    client.knative.dev/user-image: gcr.io/buffer-data/label-studio-engage:1.0.0
  labels:
    cloud.googleapis.com/location: us-central1
  name: label-studio-engage
  namespace: '655891191260'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/client-name: cloud-console
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: PROJECT_NAME
          value: engage-labels
        - name: USERNAME
          value: engage
        - name: PASSWORD
          value: buffer
        image: gcr.io/buffer-data/label-studio-engage:1.0.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
      serviceAccountName: 655891191260-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
